{"name": "Kayit Olma Kontrolü. ", "status": "failed", "statusDetails": {"message": "AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following failure was found in \"test_basarili_kayit_ol\" (test_kayit_ol.TestKayitOl):\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/standard/Desktop/Tobeto-Test-Team-Project/tests/test_kayit_ol.py\", line 19, in test_basarili_kayit_ol\n    self.soft_assert(self.assertEqual, GORUNECEKTEXT , kayit_ol_object.kaydetme_basarili(), \"MESAJ GORUNTULENEMEDİ.\")\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py\", line 887, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py\", line 717, in fail\n    raise self.failureException(msg)\nAssertionError: \"Tobe[40 chars]eşti.\" != \"Tobe[40 chars]eşti.\\nGiriş yapabilmek için e-posta adresiniz[61 chars]rin.\"\n  Tobeto Platform'a kaydınız başarıyla gerçekleşti.\n+ Giriş yapabilmek için e-posta adresinize iletilen doğrulama linkine tıklayarak hesabınızı aktifleştirin.\n : MESAJ GORUNTULENEMEDİ.\n\n-+ [1/1] +-", "trace": "self = <test_kayit_ol.TestKayitOl testMethod=test_basarili_kayit_ol>\n\n    @allure.title(\"Kayit Olma Kontrolü. \")\n    def test_basarili_kayit_ol(self):\n        kayit_ol_object = KayitOlFonksiyonu(self.driver)\n        kayit_ol_object.kayitOl_biliglerini_doldurur()\n        kayit_ol_object.sozlesmeler_sayfasini_doldurur()\n        kayit_ol_object.kaydetme_basarili()\n        self.soft_assert(self.assertEqual, GORUNECEKTEXT , kayit_ol_object.kaydetme_basarili(), \"MESAJ GORUNTULENEMEDİ.\")\n>       self.assert_all()\n\ntests/test_kayit_ol.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/softest/case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following failure was found in \"test_basarili_kayit_ol\" (test_kayit_ol.TestKayitOl):\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/standard/Desktop/Tobeto-Test-Team-Project/tests/test_kayit_ol.py\", line 19, in test_basarili_kayit_ol\nE       self.soft_assert(self.assertEqual, GORUNECEKTEXT , kayit_ol_object.kaydetme_basarili(), \"MESAJ GORUNTULENEMEDİ.\")\nE     File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py\", line 887, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py\", line 717, in fail\nE       raise self.failureException(msg)\nE   AssertionError: \"Tobe[40 chars]eşti.\" != \"Tobe[40 chars]eşti.\\nGiriş yapabilmek için e-posta adresiniz[61 chars]rin.\"\nE     Tobeto Platform'a kaydınız başarıyla gerçekleşti.\nE   + Giriş yapabilmek için e-posta adresinize iletilen doğrulama linkine tıklayarak hesabınızı aktifleştirin.\nE    : MESAJ GORUNTULENEMEDİ.\nE   \nE   -+ [1/1] +-"}, "start": 1714735234363, "stop": 1714735283742, "uuid": "6f2c6329-8e2f-41bf-95f8-ebb9b1ba4994", "historyId": "84e558f634d665129666b2bd8a4ddae5", "testCaseId": "84e558f634d665129666b2bd8a4ddae5", "fullName": "tests.test_kayit_ol.TestKayitOl#test_basarili_kayit_ol", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_kayit_ol"}, {"name": "subSuite", "value": "TestKayitOl"}, {"name": "host", "value": "elif.local"}, {"name": "thread", "value": "5840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_kayit_ol"}]}